// <auto-generated />
using System;
using BatchDemo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BatchDemo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BatchDemoDbContext))]
    partial class BatchDemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BatchDemo.Domain.Batch", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("AcceptedArtifactKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("accepted_artifact_key");

                    b.Property<int?>("AcceptedCount")
                        .HasColumnType("integer")
                        .HasColumnName("accepted_count");

                    b.Property<Guid?>("CanonicalBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("canonical_batch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("merchant_id");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("original_filename");

                    b.Property<string>("OriginalObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("original_object_key");

                    b.Property<string>("OriginalSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("original_sha256")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("ProcessingCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_completed_at");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("RejectedArtifactKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rejected_artifact_key");

                    b.Property<int?>("RejectedCount")
                        .HasColumnType("integer")
                        .HasColumnName("rejected_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("SummaryArtifactKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("summary_artifact_key");

                    b.Property<int?>("TotalRowCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_row_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("BatchId")
                        .HasName("pk_batches");

                    b.HasIndex("CanonicalBatchId");

                    b.HasIndex("OriginalObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_batches_original_object_key");

                    b.HasIndex("MerchantId", "OriginalSha256")
                        .IsUnique()
                        .HasDatabaseName("ux_batches_canonical_delivery")
                        .HasFilter("canonical_batch_id IS NULL");

                    b.ToTable("batches", null, t =>
                        {
                            t.HasCheckConstraint("ck_batches_duplicate_canonical", "(status = 'Duplicate' AND canonical_batch_id IS NOT NULL) OR (status <> 'Duplicate' AND canonical_batch_id IS NULL)");

                            t.HasCheckConstraint("ck_batches_sha256", "length(original_sha256) = 64");
                        });
                });

            modelBuilder.Entity("BatchDemo.Domain.BatchWorkItem", b =>
                {
                    b.Property<Guid>("WorkItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lease_owner");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("work_type");

                    b.HasKey("WorkItemId")
                        .HasName("pk_batch_work_items");

                    b.HasIndex("BatchId")
                        .IsUnique()
                        .HasDatabaseName("ux_batch_work_items_batch_id");

                    b.HasIndex("Status", "AvailableAt")
                        .HasDatabaseName("ix_batch_work_items_available");

                    b.ToTable("batch_work_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_batch_work_items_attempt_count", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("BatchDemo.Domain.Batch", b =>
                {
                    b.HasOne("BatchDemo.Domain.Batch", "CanonicalBatch")
                        .WithMany()
                        .HasForeignKey("CanonicalBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_batches_canonical_batch");

                    b.Navigation("CanonicalBatch");
                });

            modelBuilder.Entity("BatchDemo.Domain.BatchWorkItem", b =>
                {
                    b.HasOne("BatchDemo.Domain.Batch", "Batch")
                        .WithMany("WorkItems")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_batch_work_items_batch");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("BatchDemo.Domain.Batch", b =>
                {
                    b.Navigation("WorkItems");
                });
#pragma warning restore 612, 618
        }
    }
}
